# -*- coding: utf-8 -*-
"""agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16o83LwkGAvhdW0N-c3YVcJXt6_yP84Ww
"""

from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver
from tools import toolkit

llm = ChatOpenAI()
memory = MemorySaver()

system_prompt = """Eres un asistente especializado en zoología y conservación.
Utiliza tus herramientas para responder las consultas de los usuarios de forma precisa.
Sigue estrictamente este formato para tu respuesta final:

INFORME
---
Especie: [Nombre Común] ([Nombre Científico])
Descripción: [Resultado de identificador_taxonomico]
Estado Legal: [Resultado de consultar_estado_conservacion]
Amenazas Principales: [Resultado de resumidor_amenazas_antropicas]
Acción Recomendada: [Resultado de generador_protocolos_biologicos]"""

agent_executor = create_react_agent(
    model=llm,
    tools=toolkit,
    checkpointer=memory,
    prompt=system_prompt
)