# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e02xHmZ-ic9lQDrX6xClXGcRPGbTv7LK
"""

import os
from dotenv import load_dotenv

load_dotenv()

from agent import agent_executor

def iniciar_chat():
    print("SISTEMA DE ANÁLISIS DE ESPECIES (PERÚ)")
    print("Escribe el nombre de un animal o 'salir' para terminar.\n")

    config = {"configurable": {"thread_id": "sesion_biologia_1"}}

    while True:
        usuario = input("Usuario: ")
        if usuario.lower() in ["salir", "exit", "quit"]:
            break

        for event in agent_executor.stream(
            {"messages": [("user", usuario)]},
            config
        ):
            for value in event.values():
                if "messages" in value:
                    print(f"\nAsistente:\n{value['messages'][-1].content}\n")

if __name__ == "__main__":
    iniciar_chat()