# -*- coding: utf-8 -*-
"""tools

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycrsmlNsHuvbZ41pvDp1hQLL7cksnet6
"""

import os
from dotenv import load_dotenv

load_dotenv()

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableBranch
from langchain_community.tools.tavily_search import TavilySearchResults
from pydantic import BaseModel, Field

llm = ChatOpenAI()
tavily_tool = TavilySearchResults(max_results=3)

class EspecieInput(BaseModel):
    nombre_comun: str = Field(description="Nombre común del animal (ej. 'Oso de anteojos')")

@tool("identificador_taxonomico", args_schema=EspecieInput)
def identificador_taxonomico(nombre_comun: str) -> str:
    """Traduce un nombre común a científico y proporciona una descripción de validación."""
    prompt = ChatPromptTemplate.from_template(
        "Eres un experto en taxonomía. Para el animal '{animal}', proporciona su nombre científico "
        "y una descripción física muy breve para confirmar su identidad."
    )
    chain = prompt | llm | StrOutputParser()
    return chain.invoke({"animal": nombre_comun})

@tool("consultar_estado_conservacion")
def consultar_estado_conservacion(nombre_cientifico: str) -> str:
    """Consulta la categoría de amenaza oficial (SERFOR/IUCN) para la especie en Perú."""
    query = f"categoría de amenaza oficial SERFOR IUCN {nombre_cientifico} Perú"
    raw_data = tavily_tool.invoke(query)
    prompt = ChatPromptTemplate.from_template("De estos datos: {d}, indica solo la categoría de amenaza de {e} (ej. Vulnerable, En Peligro).")
    chain = prompt | llm | StrOutputParser()
    return chain.invoke({"d": raw_data, "e": nombre_cientifico})

@tool("resumidor_amenazas_antropicas")
def resumidor_amenazas_antropicas(nombre_cientifico: str) -> str:
    """Busca y resume de forma concisa las principales amenazas que enfrenta la especie."""
    query = f"principales amenazas antropicas {nombre_cientifico} Perú"
    raw_data = tavily_tool.invoke(query)
    prompt = ChatPromptTemplate.from_template("Resume en 2 líneas las principales amenazas para {e} basándote en: {d}")
    chain = prompt | llm | StrOutputParser()
    return chain.invoke({"d": raw_data, "e": nombre_cientifico})

class ProtocoloInput(BaseModel):
    especie: str = Field(description="Nombre científico")
    estado: str = Field(description="Categoría de amenaza")

@tool("generador_protocolos_biologicos", args_schema=ProtocoloInput)
def generador_protocolos_biologicos(especie: str, estado: str) -> str:
    """Genera un plan de acción (Rescate o Monitoreo) según el riesgo."""
    prompt_critico = ChatPromptTemplate.from_template("RESCATE: {especie}. Acción para estado {estado}...")
    prompt_monitoreo = ChatPromptTemplate.from_template("MONITOREO: {especie}. Acción para estado {estado}...")

    branch = RunnableBranch(
        (lambda x: any(e in x["estado"].lower() for e in ["peligro", "vulnerable", "critico"]), prompt_critico | llm | StrOutputParser()),
        prompt_monitoreo | llm | StrOutputParser()
    )
    return branch.invoke({"especie": especie, "estado": estado})

toolkit = [identificador_taxonomico, consultar_estado_conservacion, resumidor_amenazas_antropicas, generador_protocolos_biologicos]